package com.samseng.vehicles.model;
// Generated 23/01/2018 19:32:51 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.constraints.NotBlank;

/**
 * Briefing generated by hbm2java
 */
@Entity
@Table(name = "Briefing", schema = "dbo", catalog = "smsngvcls")
public class Briefing extends LogicDelete implements java.io.Serializable {

	private Integer id;
	private String shortDescription;
	private String longDescription;
	private short deleted = 0;
	private Set<BriefingQuestions> briefingQuestionses = new HashSet<BriefingQuestions>(0);
	private Set<VehicleType> vehicleTypes = new HashSet<VehicleType>(0);

	public Briefing() {
	}

	public Briefing(String shortDescription) {
		this.shortDescription = shortDescription;
	}

	public Briefing(String shortDescription, String longDescription, Short deleted,
			Set<BriefingQuestions> briefingQuestionses, Set<VehicleType> vehicleTypes) {
		this.shortDescription = shortDescription;
		this.longDescription = longDescription;
		this.deleted = deleted;
		this.briefingQuestionses = briefingQuestionses;
		this.vehicleTypes = vehicleTypes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "shortDescription", nullable = false, length = 100)
	@NotBlank(message = "{briefing.shortDescription.blank}")
	public String getShortDescription() {
		return this.shortDescription;
	}

	public void setShortDescription(String shortDescription) {
		this.shortDescription = shortDescription;
	}

	@Column(name = "longDescription")
	@NotBlank(message = "{briefing.longDescription.blank}")
	public String getLongDescription() {
		return this.longDescription;
	}

	public void setLongDescription(String longDescription) {
		this.longDescription = longDescription;
	}

	@Column(name = "deleted")
	public short getDeleted() {
		return this.deleted;
	}

	public void setDeleted(short deleted) {
		this.deleted = deleted;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "briefing")
	public Set<BriefingQuestions> getBriefingQuestionses() {
		return this.briefingQuestionses;
	}

	public void setBriefingQuestionses(Set<BriefingQuestions> briefingQuestionses) {
		this.briefingQuestionses = briefingQuestionses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "briefing")
	public Set<VehicleType> getVehicleTypes() {
		return this.vehicleTypes;
	}

	public void setVehicleTypes(Set<VehicleType> vehicleTypes) {
		this.vehicleTypes = vehicleTypes;
	}

}
