package com.samseng.vehicles.model;
// Generated 23/01/2018 19:32:51 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Driver generated by hbm2java
 */
@Entity
@Table(name = "Driver", schema = "dbo", catalog = "smsngvcls")
public class Driver implements java.io.Serializable {

	private Integer id;
	private Company company;
	private String documentNumber;
	private String name;
	private Date driverLicenceExpireDate;
	private Date assuranceWorkRiskExpireDate;
	private String driverLicenceNumber;
	private String afipdata;
	private String telephone;
	private short deleted;
	private Set<VehicleRegistered> vehicleRegistereds = new HashSet<VehicleRegistered>(0);

	public Driver() {
	}

	public Driver(Company company, String documentNumber, String name, short deleted) {
		this.company = company;
		this.documentNumber = documentNumber;
		this.name = name;
		this.deleted = deleted;
	}

	public Driver(Company company, String documentNumber, String name, Date driverLicenceExpireDate,
			Date assuranceWorkRiskExpireDate, String driverLicenceNumber, String afipdata, String telephone,
			short deleted, Set<VehicleRegistered> vehicleRegistereds) {
		this.company = company;
		this.documentNumber = documentNumber;
		this.name = name;
		this.driverLicenceExpireDate = driverLicenceExpireDate;
		this.assuranceWorkRiskExpireDate = assuranceWorkRiskExpireDate;
		this.driverLicenceNumber = driverLicenceNumber;
		this.afipdata = afipdata;
		this.telephone = telephone;
		this.deleted = deleted;
		this.vehicleRegistereds = vehicleRegistereds;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CompanyId", nullable = false)
	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	@Column(name = "documentNumber", nullable = false, length = 30)
	public String getDocumentNumber() {
		return this.documentNumber;
	}

	public void setDocumentNumber(String documentNumber) {
		this.documentNumber = documentNumber;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "driverLicenceExpireDate", length = 10)
	public Date getDriverLicenceExpireDate() {
		return this.driverLicenceExpireDate;
	}

	public void setDriverLicenceExpireDate(Date driverLicenceExpireDate) {
		this.driverLicenceExpireDate = driverLicenceExpireDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "assuranceWorkRiskExpireDate", length = 10)
	public Date getAssuranceWorkRiskExpireDate() {
		return this.assuranceWorkRiskExpireDate;
	}

	public void setAssuranceWorkRiskExpireDate(Date assuranceWorkRiskExpireDate) {
		this.assuranceWorkRiskExpireDate = assuranceWorkRiskExpireDate;
	}

	@Column(name = "driverLicenceNumber", length = 50)
	public String getDriverLicenceNumber() {
		return this.driverLicenceNumber;
	}

	public void setDriverLicenceNumber(String driverLicenceNumber) {
		this.driverLicenceNumber = driverLicenceNumber;
	}

	@Column(name = "AFIPData", length = 100)
	public String getAfipdata() {
		return this.afipdata;
	}

	public void setAfipdata(String afipdata) {
		this.afipdata = afipdata;
	}

	@Column(name = "Telephone", length = 50)
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Column(name = "deleted", nullable = false)
	public short getDeleted() {
		return this.deleted;
	}

	public void setDeleted(short deleted) {
		this.deleted = deleted;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "DriversRegistred", schema = "dbo", catalog = "smsngvcls", joinColumns = {
			@JoinColumn(name = "Driver_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "VehicleRegistered_id", nullable = false, updatable = false) })
	public Set<VehicleRegistered> getVehicleRegistereds() {
		return this.vehicleRegistereds;
	}

	public void setVehicleRegistereds(Set<VehicleRegistered> vehicleRegistereds) {
		this.vehicleRegistereds = vehicleRegistereds;
	}

}
