package com.samseng.vehicles.model;
// Generated 23/01/2018 19:32:51 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Sector generated by hbm2java
 */
@Entity
@Table(name = "Sector", schema = "dbo", catalog = "smsngvcls")
public class Sector extends LogicDelete implements java.io.Serializable {

	private Integer id;
	private String description;
	private short deleted;
	private Set<VehicleRegistered> vehicleRegistereds = new HashSet<VehicleRegistered>(0);
	private Set<Users> userses = new HashSet<Users>(0);

	public Sector() {
	}

	public Sector(String description, short deleted) {
		this.description = description;
		this.deleted = deleted;
	}

	public Sector(String description, short deleted, Set<VehicleRegistered> vehicleRegistereds, Set<Users> userses) {
		this.description = description;
		this.deleted = deleted;
		this.vehicleRegistereds = vehicleRegistereds;
		this.userses = userses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "description", nullable = false, length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "deleted", nullable = false)
	public short getDeleted() {
		return this.deleted;
	}

	public void setDeleted(short deleted) {
		this.deleted = deleted;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sector")
	public Set<VehicleRegistered> getVehicleRegistereds() {
		return this.vehicleRegistereds;
	}

	public void setVehicleRegistereds(Set<VehicleRegistered> vehicleRegistereds) {
		this.vehicleRegistereds = vehicleRegistereds;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "Approver", schema = "dbo", catalog = "smsngvcls", joinColumns = {
			@JoinColumn(name = "SectorId", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "UsersUsername", nullable = false, updatable = false) })
	public Set<Users> getUserses() {
		return this.userses;
	}

	public void setUserses(Set<Users> userses) {
		this.userses = userses;
	}

}
