package com.samseng.vehicles.model;
// Generated 23/01/2018 19:32:51 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VehicleLog generated by hbm2java
 */
@Entity
@Table(name = "VehicleLog", schema = "dbo", catalog = "smsngvcls")
public class VehicleLog implements java.io.Serializable {

	private Integer id;
	private VehicleRegistered vehicleRegistered;
	private VehicleStates vehicleStates;
	private int dateTimestamp;
	private String stateChangedBy;
	private String observations;
	private short lastLogRegistered;

	public VehicleLog() {
	}

	public VehicleLog(VehicleRegistered vehicleRegistered, VehicleStates vehicleStates, int dateTimestamp,
			short lastLogRegistered) {
		this.vehicleRegistered = vehicleRegistered;
		this.vehicleStates = vehicleStates;
		this.dateTimestamp = dateTimestamp;
		this.lastLogRegistered = lastLogRegistered;
	}

	public VehicleLog(VehicleRegistered vehicleRegistered, VehicleStates vehicleStates, int dateTimestamp,
			String stateChangedBy, String observations, short lastLogRegistered) {
		this.vehicleRegistered = vehicleRegistered;
		this.vehicleStates = vehicleStates;
		this.dateTimestamp = dateTimestamp;
		this.stateChangedBy = stateChangedBy;
		this.observations = observations;
		this.lastLogRegistered = lastLogRegistered;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VehicleRegisteredId", nullable = false)
	public VehicleRegistered getVehicleRegistered() {
		return this.vehicleRegistered;
	}

	public void setVehicleRegistered(VehicleRegistered vehicleRegistered) {
		this.vehicleRegistered = vehicleRegistered;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VehicleStatesId", nullable = false)
	public VehicleStates getVehicleStates() {
		return this.vehicleStates;
	}

	public void setVehicleStates(VehicleStates vehicleStates) {
		this.vehicleStates = vehicleStates;
	}

	@Column(name = "dateTimestamp", nullable = false)
	public int getDateTimestamp() {
		return this.dateTimestamp;
	}

	public void setDateTimestamp(int dateTimestamp) {
		this.dateTimestamp = dateTimestamp;
	}

	@Column(name = "stateChangedBy", length = 300)
	public String getStateChangedBy() {
		return this.stateChangedBy;
	}

	public void setStateChangedBy(String stateChangedBy) {
		this.stateChangedBy = stateChangedBy;
	}

	@Column(name = "Observations")
	public String getObservations() {
		return this.observations;
	}

	public void setObservations(String observations) {
		this.observations = observations;
	}

	@Column(name = "lastLogRegistered", nullable = false)
	public short getLastLogRegistered() {
		return this.lastLogRegistered;
	}

	public void setLastLogRegistered(short lastLogRegistered) {
		this.lastLogRegistered = lastLogRegistered;
	}

}
