package com.samseng.vehicles.model;
// Generated 23/01/2018 19:32:51 by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VehicleRegisteredCheckList generated by hbm2java
 */
@Entity
@Table(name = "VehicleRegisteredCheckList", schema = "dbo", catalog = "smsngvcls")
public class VehicleRegisteredCheckList implements java.io.Serializable {

	private VehicleRegisteredCheckListId id;
	private BriefingQuestions briefingQuestions;
	private VehicleRegistered vehicleRegistered;
	private short passed;
	private String observations;

	public VehicleRegisteredCheckList() {
	}

	public VehicleRegisteredCheckList(VehicleRegisteredCheckListId id, BriefingQuestions briefingQuestions,
			VehicleRegistered vehicleRegistered, short passed) {
		this.id = id;
		this.briefingQuestions = briefingQuestions;
		this.vehicleRegistered = vehicleRegistered;
		this.passed = passed;
	}

	public VehicleRegisteredCheckList(VehicleRegisteredCheckListId id, BriefingQuestions briefingQuestions,
			VehicleRegistered vehicleRegistered, short passed, String observations) {
		this.id = id;
		this.briefingQuestions = briefingQuestions;
		this.vehicleRegistered = vehicleRegistered;
		this.passed = passed;
		this.observations = observations;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "vehicleRegisteredId", column = @Column(name = "VehicleRegisteredId", nullable = false)),
			@AttributeOverride(name = "briefingQuestionsId", column = @Column(name = "BriefingQuestionsId", nullable = false)) })
	public VehicleRegisteredCheckListId getId() {
		return this.id;
	}

	public void setId(VehicleRegisteredCheckListId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BriefingQuestionsId", nullable = false, insertable = false, updatable = false)
	public BriefingQuestions getBriefingQuestions() {
		return this.briefingQuestions;
	}

	public void setBriefingQuestions(BriefingQuestions briefingQuestions) {
		this.briefingQuestions = briefingQuestions;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VehicleRegisteredId", nullable = false, insertable = false, updatable = false)
	public VehicleRegistered getVehicleRegistered() {
		return this.vehicleRegistered;
	}

	public void setVehicleRegistered(VehicleRegistered vehicleRegistered) {
		this.vehicleRegistered = vehicleRegistered;
	}

	@Column(name = "passed", nullable = false)
	public short getPassed() {
		return this.passed;
	}

	public void setPassed(short passed) {
		this.passed = passed;
	}

	@Column(name = "observations")
	public String getObservations() {
		return this.observations;
	}

	public void setObservations(String observations) {
		this.observations = observations;
	}

}
