package com.samseng.vehicles.model;
// Generated 23/01/2018 19:32:51 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VehicleRegistered generated by hbm2java
 */
@Entity
@Table(name = "VehicleRegistered", schema = "dbo", catalog = "smsngvcls")
public class VehicleRegistered implements java.io.Serializable {

	private Integer id;
	private Sector sector;
	private Vehicle vehicle;
	private Date dateTimestamp;
	private Set<Driver> drivers = new HashSet<Driver>(0);
	private Set<VehicleLog> vehicleLogs = new HashSet<VehicleLog>(0);
	private Set<VehicleRegisteredCheckList> vehicleRegisteredCheckLists = new HashSet<VehicleRegisteredCheckList>(0);

	public VehicleRegistered() {
	}

	public VehicleRegistered(Sector sector, Vehicle vehicle, Date dateTimestamp) {
		this.sector = sector;
		this.vehicle = vehicle;
		this.dateTimestamp = dateTimestamp;
	}

	public VehicleRegistered(Sector sector, Vehicle vehicle, Date dateTimestamp, Set<Driver> drivers,
			Set<VehicleLog> vehicleLogs, Set<VehicleRegisteredCheckList> vehicleRegisteredCheckLists) {
		this.sector = sector;
		this.vehicle = vehicle;
		this.dateTimestamp = dateTimestamp;
		this.drivers = drivers;
		this.vehicleLogs = vehicleLogs;
		this.vehicleRegisteredCheckLists = vehicleRegisteredCheckLists;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SectorId", nullable = false)
	public Sector getSector() {
		return this.sector;
	}

	public void setSector(Sector sector) {
		this.sector = sector;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VehicleId", nullable = false)
	public Vehicle getVehicle() {
		return this.vehicle;
	}

	public void setVehicle(Vehicle vehicle) {
		this.vehicle = vehicle;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateTimestamp", nullable = false, length = 23)
	public Date getDateTimestamp() {
		return this.dateTimestamp;
	}

	public void setDateTimestamp(Date dateTimestamp) {
		this.dateTimestamp = dateTimestamp;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "DriversRegistred", schema = "dbo", catalog = "smsngvcls", joinColumns = {
			@JoinColumn(name = "VehicleRegistered_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "Driver_id", nullable = false, updatable = false) })
	public Set<Driver> getDrivers() {
		return this.drivers;
	}

	public void setDrivers(Set<Driver> drivers) {
		this.drivers = drivers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vehicleRegistered")
	public Set<VehicleLog> getVehicleLogs() {
		return this.vehicleLogs;
	}

	public void setVehicleLogs(Set<VehicleLog> vehicleLogs) {
		this.vehicleLogs = vehicleLogs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vehicleRegistered")
	public Set<VehicleRegisteredCheckList> getVehicleRegisteredCheckLists() {
		return this.vehicleRegisteredCheckLists;
	}

	public void setVehicleRegisteredCheckLists(Set<VehicleRegisteredCheckList> vehicleRegisteredCheckLists) {
		this.vehicleRegisteredCheckLists = vehicleRegisteredCheckLists;
	}

}
