package com.samseng.vehicles.model;
// Generated 23/01/2018 19:32:51 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VehicleRegisteredCheckListId generated by hbm2java
 */
@Embeddable
public class VehicleRegisteredCheckListId implements java.io.Serializable {

	private int vehicleRegisteredId;
	private int briefingQuestionsId;

	public VehicleRegisteredCheckListId() {
	}

	public VehicleRegisteredCheckListId(int vehicleRegisteredId, int briefingQuestionsId) {
		this.vehicleRegisteredId = vehicleRegisteredId;
		this.briefingQuestionsId = briefingQuestionsId;
	}

	@Column(name = "VehicleRegisteredId", nullable = false)
	public int getVehicleRegisteredId() {
		return this.vehicleRegisteredId;
	}

	public void setVehicleRegisteredId(int vehicleRegisteredId) {
		this.vehicleRegisteredId = vehicleRegisteredId;
	}

	@Column(name = "BriefingQuestionsId", nullable = false)
	public int getBriefingQuestionsId() {
		return this.briefingQuestionsId;
	}

	public void setBriefingQuestionsId(int briefingQuestionsId) {
		this.briefingQuestionsId = briefingQuestionsId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VehicleRegisteredCheckListId))
			return false;
		VehicleRegisteredCheckListId castOther = (VehicleRegisteredCheckListId) other;

		return (this.getVehicleRegisteredId() == castOther.getVehicleRegisteredId())
				&& (this.getBriefingQuestionsId() == castOther.getBriefingQuestionsId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getVehicleRegisteredId();
		result = 37 * result + this.getBriefingQuestionsId();
		return result;
	}

}
