package com.samseng.vehicles.model;
// Generated 23/01/2018 19:32:51 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * VehicleStates generated by hbm2java
 */
@Entity
@Table(name = "VehicleStates", schema = "dbo", catalog = "smsngvcls")
public class VehicleStates implements java.io.Serializable {

	private Integer id;
	private String state;
	private Set<VehicleLog> vehicleLogs = new HashSet<VehicleLog>(0);

	public VehicleStates() {
	}

	public VehicleStates(String state, Set<VehicleLog> vehicleLogs) {
		this.state = state;
		this.vehicleLogs = vehicleLogs;
	}
	
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "state", length = 100)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vehicleStates")
	public Set<VehicleLog> getVehicleLogs() {
		return this.vehicleLogs;
	}

	public void setVehicleLogs(Set<VehicleLog> vehicleLogs) {
		this.vehicleLogs = vehicleLogs;
	}

}
